---

driver:
  name: docker

platforms:
  - name: sansible_gocd_server_xenial
    image: jrei/systemd-ubuntu:16.04
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: sansible_gocd_server_bionic
    image: jrei/systemd-ubuntu:18.04
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 molecule/

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

scenario:
  name: default

verifier:
  name: testinfra
